### ISSUE TITLE
Getting decorators in create react app working

### ISSUE THREAD

**Issue by from-nibly** [org-redtea/react-inversify#1]
Any way to get decorators to work in create react app for use with inversify?

I've tried using customize-cra but it doesn't seem to be keeping the class decorators or the parameter decorators.

**Comment by Hokid** [comment]
Hello, @from-nibly !

Do you import(and install before) `reflect-metadata` in the `src/index.(ts|tsx)`?

For parameter decorator to work i suggest to use this approach:

```typescript
// SomeService.ts
import {decorate, inject, injectable} from 'inversify';
import {TYPES} from './types';
import {CoreService} from './CoreService';

@injectable()
export class SomeService {
  constructor(private coreService: CoreService) {}
}

decorate(inject(TYPES.CoreService) as ParameterDecorator, SomeService, 0);
```

**Comment by from-nibly** [comment]
I'll take a look at that! Thanks! I thought I was using reflect-metadata, usually Inversify flips a biscuit when that's not installed. I'll have to take a look at my code tonight.

**Comment by from-nibly** [comment]
OK I figured it out. It looks like it was storing the annotations, it just was failing because it was a class that extended another class. I added `skipBaseClassChecks: true` to the container, and that got me through the error, For anyone wondering in the future, here is what I have as far as configuration goes.

package.json
```json
{
  "dependencies": {
    "@babel/plugin-proposal-decorators": "^7.12.1",
    "@babel/preset-typescript": "^7.12.1",
    "@redtea/react-inversify": "^1.0.1",
    "babel-plugin-parameter-decorator": "^1.0.16",
    "inversify": "4.14.0",
    "reflect-metadata": "^0.1.13",
    "typescript": "~3.9.7"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject",
  },
  "devDependencies": {
    "customize-cra": "1.0.0",
    "react-app-rewired": "^2.1.6",
    "react-scripts": "3.4.2"
  },
}
```

```js
const {
  override,
  addDecoratorsLegacy,
  useEslintRc,
  addBabelPlugin,
  addBabelPreset,
} = require('customize-cra');

module.exports = override(
  addDecoratorsLegacy(),
  useEslintRc('./.eslintrc'),
  addBabelPlugin('babel-plugin-parameter-decorator'),
  addBabelPreset(['@babel/preset-typescript', { onlyRemoveTypeImports: true }])
);
```
Notably adding the babel-plugin-parameter-decorator also allowed me to use `@inject` annotations on constructor parameters.

**Comment by Hokid** [comment]
> OK I figured it out. It looks like it was storing the annotations, it just was failing because it was a class that extended another class. I added `skipBaseClassChecks: true` to the container, and that got me through the error, For anyone wondering in the future, here is what I have as far as configuration goes.
> 
> package.json
> 
> ```json
> {
>   "dependencies": {
>     "@babel/plugin-proposal-decorators": "^7.12.1",
>     "@babel/preset-typescript": "^7.12.1",
>     "@redtea/react-inversify": "^1.0.1",
>     "babel-plugin-parameter-decorator": "^1.0.16",
>     "inversify": "4.14.0",
>     "reflect-metadata": "^0.1.13",
>     "typescript": "~3.9.7"
>   },
>   "scripts": {
>     "start": "react-app-rewired start",
>     "build": "react-app-rewired build",
>     "test": "react-app-rewired test",
>     "eject": "react-app-rewired eject",
>   },
>   "devDependencies": {
>     "customize-cra": "1.0.0",
>     "react-app-rewired": "^2.1.6",
>     "react-scripts": "3.4.2"
>   },
> }
> ```
> 
> ```js
> const {
>   override,
>   addDecoratorsLegacy,
>   useEslintRc,
>   addBabelPlugin,
>   addBabelPreset,
> } = require('customize-cra');
> 
> module.exports = override(
>   addDecoratorsLegacy(),
>   useEslintRc('./.eslintrc'),
>   addBabelPlugin('babel-plugin-parameter-decorator'),
>   addBabelPreset(['@babel/preset-typescript', { onlyRemoveTypeImports: true }])
> );
> ```
> 
> Notably adding the babel-plugin-parameter-decorator also allowed me to use `@inject` annotations on constructor parameters.

Your configuration looks very interesting! Can you add some notes to the react-inversify readme about how to make work parameter decorator in CRA environment using `babel-plugin-parameter-decorator`?
